config/routes.rb
Rails.application.routes.draw do
    
  resources :recipes

    get '/contact', to: 'home#contact', as: 'contact'

    get '/about', to: 'home#about', as: 'about'
    
    root to: 'home#index'
    
    

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
 belongs_to :category
 validates_presence_of :title, :ingredients, :instructions
    
    
def self.find_all_by_query(query)
 query = query.downcase
 query = "%#{query}%"
 Recipe.where(['lower(title) like ?', query])
end
    

def self.find_all_by_query(query)
 query = query.downcase
 query = "%#{query}%"
 Recipe.where(['lower(title) like ?
 OR lower(ingredients) like ?
 OR lower(instructions) like ?',
 query, query, query])
end    
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
private
 def authenticate
 authenticate_or_request_with_http_basic do |user_name, password|
 session[:logged_in] = (user_name == 'admin' && password == 'password')
 end
 end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
 @number_of_recipes = Recipe.count
end

  def about
  end
    
  def contact
  end      
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, :only =>[:new, :edit, :create, :update]
  before_action :authenticate, :except => [:index, :show]
      

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:q]
    @recipes = Recipe.find_all_by_query(params[:q])
    else
    @recipes = Recipe.all
  end
end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
    def new
     @recipe = Recipe.new
     @categories = Category.all.collect{|c| [c.name, c.id] }
    end

  # GET /recipes/1/edit
  def edit
    @categories = Category.all.collect{|c| [c.name, c.id] }
  end
    
    

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
     @recipe = Recipe.includes(:category).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
       params.require(:recipe).permit(:title, :ingredients, :instructions, :category_id)
    end
    
    def get_categories
      @categories = Category.all.collect{|c| [c.name, c.id] }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/about.html.erb
<h2>About</h2>
<p>This is a simple cookbook application I wrote. I hope you like it.</p>

app/views/home/contact.html.erb
<h2>Contact</h2>

app/views/home/index.html.erb
<%= render "/shared/search" %>
<h2>Latest Recipes</h2>
<p>There are <%= @number_of_recipes %> recipes total.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
    <head>
    <title>Cookbook</title>
    <%= stylesheet_link_tag 'application',
    media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>    
    </head>
    <body>
        <div class="container">
            <header>
                <h1>Our Cookbook</h1>
            </header>
            <section class="content">
                <nav>
                    <%=link_to_unless_current 'Home', root_url %>
                    <%=link_to_unless_current 'Recipes', recipes_url %>
                    <%=link_to_unless_current 'About', about_url %>
                    <%=link_to_unless_current 'Contact', contact_url %>
                    <% if notice %>
                     <div id="notice">
                     <%= notice %>
                     </div>
                    <% end %>
                </nav>
                <%= yield %>
            </section>
            <footer>
                <h4>Copyright <%=Date.today.year %> OurCookbook</h4>
            </footer>
        </div>
    </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>

<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%= render "/shared/search" %>
<h1>Listing recipes</h1>
<table>
 <tr>
 <th>Title</th>
 <th>Category</th>
 <th>Last Updated</th>
 <th colspan="2">&nbsp;</th>
 </tr>
 <% @recipes.each do |recipe| %>
 <tr>
 <td><%= link_to recipe.title, recipe %></td>
 <td><%= recipe.category.name rescue "No category" %></td>
 <td><%= time_ago_in_words(recipe.updated_at) %> ago</td>
 <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
 <td><%= button_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete
 %></td>
 </tr>
 <% end %>
</table>
<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<article>
 <header>
 <h2>
 <%= @recipe.title %>
 [ <%= link_to 'Edit', edit_recipe_path(@recipe) %> ]
 </h2>
 </header>
 <h3>Ingredients:</h3>
 <p><%= @recipe.ingredients %></p>
 <h3>Instructions</h3>
 <p><%= @recipe.instructions %></p>
</article>
<p><%= link_to 'Back', recipes_path %></p>

app/views/shared/_search.html.erb
<%= form_tag recipes_url, method: :get do %>
 <label for="query">Keywords: </label>
 <input type="search" id="query" name="q" value="<%= params[:q] %>">
 <input type="submit" value="Search">
<% end %>